name=dbz-source-postgres-src_db-products
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1

database.hostname=host.docker.internal
database.port=5432
database.user=postgres
database.password=postgres
database.dbname=src_db

plugin.name=pgoutput
slot.name=debezium_slot
publication.autocreate.mode=filtered

topic.prefix=dbz-source-postgres-src_db-products
schema.include.list=public
table.include.list=public.products

snapshot.mode=initial

# Jangan kirim tombstone
tombstones.on.delete=false

# SMT unwrap
transforms=unwrap
transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
transforms.unwrap.drop.tombstones=true
transforms.unwrap.delete.handling.mode=none

# PENTING: timestamp jadi Kafka Connect Timestamp (millis)
time.precision.mode=connect