name=jdbc-source-postgres-mdp-vw_products
connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
tasks.max=1
connection.url=jdbc:postgresql://host.docker.internal:5432/src_db
connection.user=postgres
connection.password=postgres
query=SELECT id, name, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM public.vw_products
mode=timestamp+incrementing
timestamp.column.name=updated_at
incrementing.column.name=id
topic.prefix=postgres-mdp-vw_products
poll.interval.ms=1000
